16:57:17.090 com.ibm.rmi.corba.ClientDelegate invoke:697 P=727970:O=0:CT ORBRas[default] Received SystemException org.omg.CORBA.UNKNOWN: 
	>> SERVER (id=4773e3aa, host=01hw824061) TRACE START:
	>>    javax.ejb.EJBException: See nested exception; nested exception is: <openjpa-2.2.3-SNAPSHOT-r422266:1642995 nonfatal user error> org.apache.openjpa.persistence.ArgumentException: Encountered new object in persistent field "sample.jee.bean.jpa.ReconPoint.reconPointDistributions<element:class sample.jee.bean.jpa.ReconPointDistribution>" during attach.  However, this field does not allow cascade attach. Set the cascade attribute for this field to CascadeType.MERGE or CascadeType.ALL (JPA annotations) or "merge" or "all" (JPA orm.xml). You cannot attach a reference to a new object without cascading.
FailedObject: sample.jee.bean.jpa.ReconPointDistribution@7634dc82
	>>	 at com.ibm.ejs.container.util.ExceptionUtil.EJBException(ExceptionUtil.java:475)
	>>	 at com.ibm.ejs.container.util.ExceptionUtil.EJBException(ExceptionUtil.java:365)
	>>	 at com.ibm.ejs.container.BusinessExceptionMappingStrategy.mapException(BusinessExceptionMappingStrategy.java:392)
	>>	 at com.ibm.ejs.container.BusinessExceptionMappingStrategy.setUncheckedException(BusinessExceptionMappingStrategy.java:554)
	>>	 at com.ibm.ejs.container.EJSDeployedSupport.setUncheckedLocalException(EJSDeployedSupport.java:567)
	>>	 at sample.jee.bean.EJSRemote0SLReconPointManagerBean_0fc22fa6.save(EJSRemote0SLReconPointManagerBean_0fc22fa6.java)
	>>	 at sample.jee.bean._EJSRemote0SLReconPointManagerBean_0fc22fa6_Tie.save(_EJSRemote0SLReconPointManagerBean_0fc22fa6_Tie.java:1)
	>>	 at sample.jee.bean._EJSRemote0SLReconPointManagerBean_0fc22fa6_Tie._invoke(_EJSRemote0SLReconPointManagerBean_0fc22fa6_Tie.java)
	>>	 at com.ibm.CORBA.iiop.ServerDelegate.dispatchInvokeHandler(ServerDelegate.java:669)
	>>	 at com.ibm.CORBA.iiop.ServerDelegate.dispatch(ServerDelegate.java:523)
	>>	 at com.ibm.rmi.iiop.ORB.process(ORB.java:523)
	>>	 at com.ibm.CORBA.iiop.ORB.process(ORB.java:1575)
	>>	 at com.ibm.rmi.iiop.Connection.doRequestWork(Connection.java:3039)
	>>	 at com.ibm.rmi.iiop.Connection.doWork(Connection.java:2922)
	>>	 at com.ibm.rmi.iiop.WorkUnitImpl.doWork(WorkUnitImpl.java:64)
	>>	 at com.ibm.ejs.oa.pool.PooledThread.run(ThreadPool.java:118)
	>>	 at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1881)
	>> SERVER (id=4773e3aa, host=01hw824061) TRACE END.
  vmcid: 0x4942f000  minor code: 3718 completed: Maybe 
16:57:17.193 com.ibm.rmi.corba.ClientDelegate invoke:730 P=727970:O=0:CT ORBRas[default] Throwable from UnknownExceptionInfo javax.ejb.EJBException: See nested exception 
